
-- AI-generated quizzes table (stores quizzes generated by AI from video content)
CREATE TABLE public.ai_quizzes (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  video_id uuid REFERENCES public.videos(id) ON DELETE CASCADE NOT NULL,
  questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  difficulty text NOT NULL DEFAULT 'medium',
  question_count integer NOT NULL DEFAULT 5,
  generated_from text NOT NULL DEFAULT 'metadata',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Watch analytics table (tracks detailed viewing patterns)
CREATE TABLE public.watch_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL,
  video_id text NOT NULL,
  watch_segments jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_watch_time integer NOT NULL DEFAULT 0,
  rewatch_count integer NOT NULL DEFAULT 0,
  drop_off_point integer DEFAULT NULL,
  max_position integer NOT NULL DEFAULT 0,
  session_count integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(user_id, video_id)
);

-- Study plans table
CREATE TABLE public.study_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL,
  plan_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  week_start date NOT NULL,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE(user_id, week_start)
);

-- Enable RLS
ALTER TABLE public.ai_quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watch_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.study_plans ENABLE ROW LEVEL SECURITY;

-- AI Quizzes: anyone can read (they're generated from public videos), admins can manage
CREATE POLICY "Anyone can view AI quizzes" ON public.ai_quizzes
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage AI quizzes" ON public.ai_quizzes
  FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- Watch analytics: users own their data, admins can view all
CREATE POLICY "Users can manage own watch analytics" ON public.watch_analytics
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all watch analytics" ON public.watch_analytics
  FOR SELECT USING (has_role(auth.uid(), 'admin'::app_role));

-- Study plans: users own their plans, admins can view all
CREATE POLICY "Users can manage own study plans" ON public.study_plans
  FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all study plans" ON public.study_plans
  FOR SELECT USING (has_role(auth.uid(), 'admin'::app_role));

-- Triggers for updated_at
CREATE TRIGGER update_ai_quizzes_updated_at
  BEFORE UPDATE ON public.ai_quizzes
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_watch_analytics_updated_at
  BEFORE UPDATE ON public.watch_analytics
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_study_plans_updated_at
  BEFORE UPDATE ON public.study_plans
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Enable realtime for watch analytics (for admin dashboard)
ALTER PUBLICATION supabase_realtime ADD TABLE public.watch_analytics;
ALTER PUBLICATION supabase_realtime ADD TABLE public.study_plans;
